---

ansible_connection: local
#postgres_git_url: "git://git.postgresql.org/git/2ndquadrant_bdr.git"
#postgres_git_ref: "bdr-pg/REL9_4_STABLE"
postgres_git_reference_repo: "/home/craig/projects/2Q/postgres-bdr"
postgres_git_checkout_dir: "/home/craig/tmp/ansible-bdr/pg-src"
# vpath build seems broken for bdr-pg
# postgres_git_builddir: "/home/craig/tmp/ansible-bdr/pg-build"
postgres_git_install_dir: "/home/craig/tmp/ansible-bdr/pg-install"
postgres_datadir: "/home/craig/tmp/ansible-bdr/pg-data-{{inventory_hostname}}"
postgres_git_install: false

bdr_ext_git_checkout_dir: "/home/craig/projects/2Q/postgres-bdr-extension"
bdr_ext_builddir: "/home/craig/tmp/ansible-bdr/bdr-ext-build"
