---

bdrgroupname: 'bdrnodes07'

ansible_connection: local
#postgres_git_url: "git://git.postgresql.org/git/2ndquadrant_bdr.git"
#postgres_git_ref: "bdr-pg/REL9_4_STABLE"
postgres_git_reference_repo: "/home/craig/projects/2Q/postgres-bdr"
postgres_git_checkout_dir: "/home/craig/tmp/ansible-bdr/pg-src-07"
# vpath build seems broken for bdr-pg
# postgres_git_builddir: "/home/craig/tmp/ansible-bdr/pg-build"
postgres_git_install_dir: "/home/craig/tmp/ansible-bdr/pg-install-07"
postgres_git_extra_configure_opts: ["--enable-debug","--enable-cassert","CFLAGS=-fno-omit-frame-pointer -ggdb -Og"]
postgres_datadir: "/home/craig/tmp/ansible-bdr/pg-data-{{inventory_hostname}}"
# TODO
# This is overridden because we can't see role defaults in cross-host host_vars
# queries. It can be removed once we add DSN fact collection.
postgres_superuser: "postgres"
# overridden per-host
postgres_git_install: false

bdr_node_database: "bdr_testdb"
bdr_first_nodename: "{{groups[bdrgroupname][0]}}"
