---

- name: Wait for peers to catch up
  command: "{{postgres_install_dir}}/bin/psql -qAtw '{{bdr_node_dsn}}' -c \"SELECT pg_xlog_wait_remote_apply(pg_current_xlog_location(), 0);\""

- name: Get inserted rows
  command: "{{postgres_install_dir}}/bin/psql -qAtw '{{bdr_node_dsn}}' -c \"SELECT string_agg(node_name, ',' ORDER BY node_name COLLATE \\\"C\\\") FROM {{bdr_check_table}};\""
  register: node_list
  failed_when: node_list.stdout|trim != groups[bdrgroupname]|sort|join(',')

- name: Get inserted rows (global seq)
  command: "{{postgres_install_dir}}/bin/psql -qAtw '{{bdr_node_dsn}}' -c \"SELECT string_agg(node_name, ',' ORDER BY node_name COLLATE \\\"C\\\") FROM {{bdr_check_table}}_globalseq;\""
  register: node_list
  failed_when: node_list.stdout|trim != groups[bdrgroupname]|sort|join(',')
