---

# This shouldn't be necessary as bdr_join_wait_for_node_ready should be enough. But isn't, apparently.
#- name: Wait for BDR to really be ready
#pause: seconds=10

- name: Force a dummy transaction so there is something to replay
  command: "{{postgres_install_dir}}/bin/psql -qAtw '{{bdr_node_dsn}}' -c \"UPDATE bdr.bdr_nodes SET node_status = node_status;\""
  when: groups[bdrgroupname][0] == inventory_hostname

- name: Ensure peers are caught up
  command: "{{postgres_install_dir}}/bin/psql -qAtw '{{bdr_node_dsn}}' -c \"SELECT pg_xlog_wait_remote_apply(pg_current_xlog_location(), 0);\""
  when: groups[bdrgroupname][0] == inventory_hostname

- name: CREATE TABLE bdr_check
  command: "{{postgres_install_dir}}/bin/psql -qAt '{{bdr_node_dsn}}' -c 'CREATE TABLE {{bdr_check_table}} (node_name text primary key);' "
  when: groups[bdrgroupname][0] == inventory_hostname

- name: Wait for CREATE TABLE to replicate
  command: "{{postgres_install_dir}}/bin/psql -qAtw '{{bdr_node_dsn}}' -c \"SELECT pg_xlog_wait_remote_apply(pg_current_xlog_location(), 0);\""
  when: groups[bdrgroupname][0] == inventory_hostname
