---

- name: DROP TABLE bdr_check
  command: "{{postgres_install_dir}}/bin/psql -qAt '{{bdr_node_dsn}}' -c 'DROP TABLE {{bdr_check_table}};' "

- name: DROP TABLE bdr_check_globalseq
  command: "{{postgres_install_dir}}/bin/psql -qAt '{{bdr_node_dsn}}' -c 'DROP TABLE {{bdr_check_table}}_globalseq;' "
