---
postgres_git_url: "git://git.postgresql.org/git/2ndquadrant_bdr.git"
postgres_git_ref: "bdr-pg/REL9_4_STABLE"

postgresql_conf_entries:
  wal_level: "'logical'"
  shared_preload_libraries: "'bdr'"
  max_connections: 200
  max_worker_processes: 100
  max_replication_slots: 100
  max_wal_senders: 100
  track_commit_timestamp: "'on'"
  logging_collector: "'on'"
  log_statement: "'all'"
  # If you want to default to BDR global sequences:
  #default_sequenceam: "'bdr'"

pg_hba_conf_entries:
  - "local   all             all                                    trust"
  - "host    all             all             127.0.0.1/32           trust"
  - "host    all             all             ::1/128                trust"
  - "local   replication     all                                    trust"
  - "host    replication     all             127.0.0.1/32           trust"
  - "host    replication     all             ::1/128                trust"

bdr_pre_create_sql_template: bdr_pre_create_sql_template.sql.j2
bdr_post_create_sql_template: bdr_post_create_sql_template.sql.j2
bdr_pre_join_sql_template: bdr_pre_join_sql_template.sql.j2
bdr_post_join_sql_template: bdr_post_join_sql_template.sql.j2
