---
# Required:
#bdr_ext_git_checkout_dir:

bdr_ext_git_install: true
bdr_ext_rpm_install: false

bdr_ext_git_url: "git@github.com:2ndQuadrant/bdr.git"
bdr_ext_git_ref: "bdr-plugin/next"
bdr_ext_pg_config: "{{postgres_git_install_dir}}/bin/pg_config"
# local path of git repo to use as a reference when cloning, if any
bdr_ext_git_reference_repo: ""

bdr_ext_git_makeclean: false

# If set to something other than the checkout dir, do a vpath
# build.
bdr_ext_git_builddir: "{{bdr_ext_git_checkout_dir}}"

bdr_ext_git_extra_configure_opts: []

# configure environment, e.g
#    CC: "ccache gcc"
bdr_ext_git_extra_configure_env: {}

bdr_ext_git_make_command: "{{postgres_git_make_command}}"

bdr_ext_git_make_targets:
  - "all"

bdr_ext_git_make_install_targets:
  - "install"
