---

# Modify the postgresql.conf to add a new bdr.bdr_connections entry
# To do that we have to extract the current one and append to it.

- name: get current bdr.connections from sql
  shell: "{{postgres_install_dir}}/bin/psql -qAtw '{{bdr_node_dsn}}' -c 'SHOW bdr.connections'"
  register: old_connections

- name: re-generate conf.d snippet for bdr with new connections
  template: src="zz_bdr_upgrade.conf.j2" dest="{{postgres_datadir}}/conf.d/bdr07_ansible.conf"

- name: Restart PostgreSQL
  shell: "ulimit -c unlimited; {{postgres_git_install_dir}}/bin/pg_ctl -D {{postgres_datadir}} -w -m fast restart"
  environment:
    PATH: "{{postgres_git_install_dir}}/bin:{{ansible_env.PATH}}"
    PGUSER: "{{postgres_superuser}}"

# The 0.7.x instances will now be ready for 0.9.x nodes to join. Hopefully.
