---

# This is a copy of roles/bdr_node/tasks/bdr_group_join.yml
# modified to join a 0.7.x master instead

- name: Set bdr_join_target_dsn fact
  set_fact:
    bdr_join_target_dsn: "port={{hostvars[groups[oldbdrgroupname][0]]['postgres_port']}} user={{hostvars[groups[oldbdrgroupname][0]]['postgres_superuser']}} dbname={{hostvars[groups[oldbdrgroupname][0]]['bdr_node_database']}}"

- name: Wait for the target node to be ready to be joined
  shell: "{{postgres_install_dir}}/bin/psql '{{bdr_join_target_dsn}}' -qAtw 'SELECT bdr.bdr_node_join_wait_for_ready();'"

- name: bdr_group_join
  shell: "{{postgres_install_dir}}/bin/psql '{{bdr_node_dsn}}' -qAtw -c \"SELECT bdr.bdr_group_join(local_node_name := '{{inventory_hostname}}', node_external_dsn := '{{bdr_node_dsn}}', join_using_dsn := '{{bdr_join_target_dsn}}');\""

- name: Wait for the join to complete
  shell: "{{postgres_install_dir}}/bin/psql '{{bdr_node_dsn}}' -qAtw 'SELECT bdr.bdr_node_join_wait_for_ready();'"
