---

- include: stop_postgres.yml
  when: postgres_cleanup

# install pglogical_output extension
- include: pglogical_ext_install_git.yml tags=pglogical_ext_install
  when: pglogical_ext_git_install

# install pglogical extension
- include: pglogical_ext_client_install_git.yml tags=pglogical_ext_client_install
  when: pglogical_ext_client_git_install

- include: stop_postgres.yml
  when: postgres_cleanup
