---

# TODO: Implement a 'psql' module

- include: get_sysid.yml
- include: set_dsn.yml
- include: start_postgres.yml
- include: create_db_exts.yml
- include: stop_postgres.yml
- include: bdr07_config.yml
- include: start_postgres.yml
- include: show_dsn.yml
