---
postgres_git_url: "git@github.com:2ndQuadrant/bdr.git"
#postgres_git_ref: "old/bdr-REL0_7_STABLE"

bdr07_postgresql_conf_entries:
  wal_level: "'logical'"
  shared_preload_libraries: "'bdr'"
  max_connections: 200
  max_worker_processes: 100
  max_replication_slots: 100
  max_wal_senders: 100
  track_commit_timestamp: "'on'"
  logging_collector: "'on'"
  log_statement: "'all'"
  log_error_verbosity: "'verbose'"
  log_min_messages: "'debug2'"
  log_line_prefix: "'%t %p:%l %v:%t %a: '"

bdr07_pg_hba_conf_entries:
  - "local   all             all                                    trust"
  - "host    all             all             127.0.0.1/32           trust"
  - "host    all             all             ::1/128                trust"
  - "local   replication     all                                    trust"
  - "host    replication     all             127.0.0.1/32           trust"
  - "host    replication     all             ::1/128                trust"

bdr07_conf_d_template: "ansible_bdr07.conf.j2"
