---

- name: Show join target dsn before we do tests
  debug: var=bdr_join_target_dsn

- name: verify our node is present and ready on join target
  command: "{{postgres_install_dir}}/bin/psql '{{bdr_join_target_dsn}}' -qAtw -c \"SELECT node_status FROM bdr.bdr_nodes WHERE node_sysid = '{{bdr_node_sysid}}'\""
  register: out
  when: inventory_hostname != bdr_first_nodename
  failed_when: out.stdout|trim != 'r'

- name: Verify all nodes are 'r'eady on join target
  command: "{{postgres_install_dir}}/bin/psql '{{bdr_join_target_dsn}}' -qAtw -c \"SELECT count(*) = count(node_status) filter (where node_status = 'r') FROM bdr.bdr_nodes\""
  register: out
  when: inventory_hostname != bdr_first_nodename
  failed_when: out.stdout|trim != 't'

- name: Verify all nodes are 'r'eady on new node
  command: "{{postgres_install_dir}}/bin/psql '{{bdr_node_dsn}}' -qAtw -c \"SELECT count(*) = count(node_status) filter (where node_status = 'r') FROM bdr.bdr_nodes\""
  register: out
  failed_when: out.stdout|trim != 't'
