- name: CREATE DATABASE
  command: "{{postgres_install_dir}}/bin/createdb --maintenance-db='{{bdr_node_dsn}} dbname=postgres' {{bdr_node_database}}"

- name: CREATE EXTENSION btree_gist
  command: "{{postgres_install_dir}}/bin/psql '{{bdr_node_dsn}}' -qAtw -c 'CREATE EXTENSION btree_gist;'"

- name: CREATE EXTENSION bdr
  command: "{{postgres_install_dir}}/bin/psql '{{bdr_node_dsn}}' -qAtw -c 'CREATE EXTENSION bdr;'"
