---

# TODO: Implement a 'psql' module
- include: set_dsn.yml
- include: start_postgres.yml
- include: create_db_exts.yml
- include: bdr_group_create.yml
  when: bdr_join and inventory_hostname == bdr_first_nodename and groups[bdrgroupname]|length > 1
- include: bdr_group_join.yml
  when: bdr_join and inventory_hostname != bdr_first_nodename
- include: show_dsn.yml
