---

# TODO: Implement a 'psql' module
# TODO: Should separate bdr_join into separate role
- include: set_dsn.yml
- include: get_sysid.yml
- include: start_postgres.yml
  when: not bdr_join_only
- include: create_db_exts.yml
  when: not bdr_join_only
- include: bdr_group_create.yml
  when: bdr_join and inventory_hostname == bdr_first_nodename and groups[bdrgroupname]|length > 1
- include: bdr_group_join.yml
  when: bdr_join and inventory_hostname != bdr_first_nodename
- include: show_dsn.yml
- include: confirm_joined.yml
  when: bdr_join and groups[bdrgroupname]|length > 1
